# Generated by Django 4.2.5 on 2023-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_data', models.TextField()),
                ('tag', models.TextField()),
                ('image', models.TextField()),
                ('user_id', models.TextField()),
                ('like_count', models.IntegerField()),
                ('upload_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True))
            ],
        ),
    ]
